#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 11:30:06 2019

@author: redha
"""

import numpy as np 
import sys
sys.path.insert(0, '../AccousticLevitator/')
from UltrasonicLevitator import *
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

origin=[0,0,0] # Point where all TDs are facing set as origin
R=75 # Radius of sphere that mould is made from in mm

tdsys=ParticleSystem() # Initiates transducer system that contains our transducers

xs, ys, zs =[], [], [] # Coordinates to plot to make sure positions are right

for theta in np.radians([75,65,55,45]): # angle of td along hemisphere face
    for i in range(25): # 25 tds in each circle
        # cylindrical coordinates 
        r = R*np.sin(theta)
        z = -R*np.cos(theta)
        phi = 2*np.pi/25*i
    
        # Cartesian coordinates
        x = r*np.cos(phi)
        y = r*np.sin(phi)
        # z=z here 
        
        # Adds to coordinates for plotting
        xs.append(x)
        ys.append(y)
        zs.append(z)
        
        pos=Vector([x,y,z]) # Position and director of transducer
        
        tdsys.appendTransducer(pos,pos) # adds Transducer to system
        
        
# Plotting 
        
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(xs, ys, zs)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

plt.show()